name: Waka Readme

on:
  schedule:
    # Runs at 00:00 IST (18:30 UTC) every 2nd day of the month
      - cron: '30 18 1-31/2 * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN:           ${{ secrets.GH_TOKEN }}
          COMMIT_BY_ME:       "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_LOC_CHART:     "False"
          SHOW_PROJECTS:      "False"
          SHOW_LANGUAGE:      "False"
          SHOW_EDITORS:       "False"
          SHOW_TIMEZONE:      "False"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_PROFILE_VIEWS:   "False"
          SHOW_OS:              "False"
